function(add_alertme_test tname binary)
  set(bin_full_path ${EXECUTABLE_OUTPUT_PATH}/${binary})
  if(CHECK_BUILD)
    add_test(check_${tname} ${bin_full_path} ${ARGN})
  endif(CHECK_BUILD)
  if(MEMCHECK_BUILD)
    set(memcheck_command "${CMAKE_MEMORYCHECK_COMMAND} ${CMAKE_MEMORYCHECK_COMMAND_OPTIONS}")
    separate_arguments(memcheck_command)
    add_test(memcheck_${tname} ${memcheck_command} ${bin_full_path} ${ARGN})
  endif(MEMCHECK_BUILD)
endfunction(add_alertme_test)